### ISSUE TITLE
Issue getting import/require style detection working

### ISSUE THREAD

**Issue by tnrich** [ganemone/NodeRequirer#98] opened 2016-10-10 16:54 UTC
Hey there,

I'm a huge fan of this library and actually ported the functionality to Atom: https://github.com/tnrich/atom-node-requirer

One thing I like about my implementation in Atom is that `Cmd-i` allows you to use the "import" syntax whereas `Cmd-shift-i` gets you the "require" style syntax.

What if instead of having the style detection, there was simply a different shortcut to do either import or require. 

The main reason I ask this is because I have been unable to get the detection to work and sometimes have files with both syntax type. 

Thanks very much!
-T

**Comment by dantman** [comment] 2016-10-10 23:37
It's probably not explained in the README but you can also define a per-project import setting in an `.noderequirer.json` file.

More keyboard shortcuts doesn't sound like a good idea. NodeRequirer already has 2 (one to import a module and another to instead attempt to import specific exports from the file) adding keyboard shortcuts would mean NodeRequirer takes up 4 shortcuts which are an already limited resource. IMHO it's also an ugly solution, you shouldn't have to use one hotkey for one project and another for a different project using a different style; your editor should be smart enough to handle that itself just like indentation.

If your issue with getting detection to work is with NodeRequirer it would be nice to have steps to reproduce the issue; also console output would be helpful.

----

Thanks for starting work on an Atom version, that's one of the things I didn't like not having when I was using Atom. IMHO it would be ideal if your plugin was also as smart as possible; with appropriate detection and config.

As I understand it Atom plugins have MUCH more control over the interface than Sublime plugins; I could imagine a few ways you could handle this better than NodeRequirer.

Firstly, why not make this easily controllable the way tabs are: When editing a JS file display an indicator with the import style in the footer near the tab setting and when clicked open a picker listing import types.

You could also look into attempting to save a per-project setting. Whether that means reusing the `.noderequirer.json` file, your own cson file, hoping atom/atom#5168 gets fixed, or hooking into project plugins (Project Manger has project settings; Project Ring doesn't have a settings API but IIRC it wouldn't be much coding). And a command from the command pallet could easily control the per-project setting.

There's also another idea of mine that could be useful to you. Awhile ago with #38 I experimented with triggering NodeRequirer via a `require([module])` snippet in the completion panel. From what I see, this flow should work in Atom as well; and maybe the interface to implement it is better in Atom. And as a bonus, require vs. import is implicit because require and import syntax would be different snippets triggered by completions triggered by typing different words.

**Comment by tnrich** [comment] 2016-10-12 06:33
Hey @dantman, thanks for the response. I'll check into the noderequirer.json file as a potential solution. How is the auto detection supposed to work? Perhaps I've set my config up incorrectly but I've never seen it function properly. Either it always does es6 import (with auto detect enabled) or it does a require if autocorrect isn't enabled. Even if I'm in a file with multiple require statements at the top, it still defaulted to import when I had autodetect turned on. I like the idea of triggering the module from a snippet.

**Comment by tnrich** [comment] 2016-10-14 07:27
Here is a gif of the import detection not working..
![asdfasdfasd](https://cloud.githubusercontent.com/assets/2730609/19378996/b85849a0-91a4-11e6-8d19-b19c12661c8f.gif)

Can you tell if I'm doing something wrong with my config? 

Thanks!

**Comment by tnrich** [comment] 2016-10-21 05:15
@dantman is the above gif enough to give you something to go on for the import detection style not working? This is still a pretty big issue for me. I'd love a way to have require/import come in correctly. 

Can you explain more on how the style detection is supposed to work? Am I doing anything wrong when setting it up?

Thanks for the help,
Thomas

**Comment by megawac** [comment] 2016-10-24 18:43
Should be fixed if you update NodeRequirer via package control @tnrich (pushed a new version)

**Closed by megawac** 2016-10-24 18:43 UTC

**Comment by tnrich** [comment] 2016-10-24 18:58
Awesome thanks @megawac !!

**Comment by tnrich** [comment] 2016-10-25 18:13
Oh interesting. How does the package control version get updated?

**Comment by megawac** [comment] 2016-10-25 18:30
Package control monitors `git tag`s on this repo
